import Vue from 'vue'
import { Tab, Tabs, Popup, Area, Button, Form, Field, Checkbox, Dialog, ActionSheet, Icon, Search, Swipe, SwipeItem, Grid, GridItem, Toast, Rate, Tabbar, TabbarItem, NavBar } from 'vant'

Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Popup)
Vue.use(Area)
Vue.use(Button)
Vue.use(Form)
Vue.use(Field)
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(ActionSheet)
Vue.use(Toast)
Vue.use(Icon)
Vue.use(Tabbar)
Vue.use(NavBar)
Vue.use(TabbarItem)
Vue.use(Rate)
Vue.use(GridItem)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
